version: "3.8"

services:
  nginx:
    build: 
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: fa2c1st/nginx_fusion:v1
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - nwfusion
    depends_on:
      - fusion1
      - fusion2
      - fusion3

  pfusion:
    build:
      dockerfile: ./docker/pgfusion.dockerfile
      context: .
    image: fa2c1st/pgfusion:v1
    container_name: pgfusion
    ports:
      - "5432"
    networks:
      - nwfusion
    volumes:
      -pgdata:/var/lib/postgressql/data

  fusion1:
    build:
      dockerfile: ./docker/fusion.dockerfile
      context: .
    image: fa2c1st/fusion:v1
    container: fusion1
    ports:
      - "8000"
    networks:
      - nwfusion
    depends_on:
      - pgfusion

  fusion2:
    build:
      dockerfile: ./docker/fusion.dockerfile
      context: .
    image: fa2c1st/fusion:v1
    container: fusion2
    ports:
      - "8000"
    networks:
      - nwfusion
    depends_on:
      - pgfusion

  fusion3:
    build:
      dockerfile: ./docker/fusion.dockerfile
      context: .
    image: fa2c1st/fusion:v1
    container: fusion3
    ports:
      - "8000"
    networks:
      - nwfusion
    depends_on:
      - pgfusion

  networks:
    wnfusion:
      driver: bridge
      
  volumes:
    pgdata: